//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LotterySyndicate.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Prize
    {
        [DisplayName("")]
        public int ID { get; set; }
        [DisplayName("Prize")]
        public Nullable<decimal> Value { get; set; }
        [DisplayName("Winning Number")]
        public Nullable<int> WinningNumber { get; set; 
}
    }
}
